spring:
  config:
    import: kafka.yml
  application:
    name: t1-java-demof
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/t1_demo}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:tst}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: ${DATABASE_SCHEMA:public}
      jdbc.batch_size: ${DATASOURCE_BATCH_SIZE:50}
      order_inserts: true
      order_updates: true
    show-sql: ${SHOW_SQL:false}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

logging:
  level:
    ROOT: INFO
    org.apache.kafka: ERROR
    ru.t1.java.demo.controller.ClientController: DEBUG

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health, prometheus
  endpoint:
    health.enabled: true
    prometheus.enabled: true
