CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT PRIMARY KEY,
    username VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR (250) NOT NULL,
    role VARCHAR (30) NOT NULL
);
